/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BookmarkSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'postId', 'userId'] as const
  $columns = BookmarkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare postId: number
  @column()
  declare userId: number
}

export class CommentSchema extends BaseModel {
  static $columns = [
    'content',
    'createdAt',
    'id',
    'parentId',
    'postId',
    'updatedAt',
    'userId',
  ] as const
  $columns = CommentSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare parentId: number | null
  @column()
  declare postId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class FollowSchema extends BaseModel {
  static $columns = ['createdAt', 'followerId', 'followingId', 'id'] as const
  $columns = FollowSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare followerId: number
  @column()
  declare followingId: number
  @column({ isPrimary: true })
  declare id: number
}

export class LikeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'postId', 'userId'] as const
  $columns = LikeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare postId: number
  @column()
  declare userId: number
}

export class NotificationSchema extends BaseModel {
  static $columns = [
    'actorId',
    'createdAt',
    'id',
    'readAt',
    'recipientId',
    'subjectId',
    'type',
  ] as const
  $columns = NotificationSchema.$columns
  @column()
  declare actorId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare recipientId: number
  @column()
  declare subjectId: number | null
  @column()
  declare type: string
}

export class PostSchema extends BaseModel {
  static $columns = [
    'commentsCount',
    'content',
    'createdAt',
    'id',
    'likesCount',
    'mediaUrl',
    'parentId',
    'updatedAt',
    'userId',
  ] as const
  $columns = PostSchema.$columns
  @column()
  declare commentsCount: number
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare likesCount: number
  @column()
  declare mediaUrl: string | null
  @column()
  declare parentId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'avatarUrl',
    'bio',
    'createdAt',
    'email',
    'followersCount',
    'followingCount',
    'fullName',
    'id',
    'password',
    'postsCount',
    'updatedAt',
    'username',
    'website',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare followersCount: number
  @column()
  declare followingCount: number
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare postsCount: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
  @column()
  declare website: string | null
}
